spring.application.name=project
# --- Configuración de la base de datos ---
spring.datasource.url=jdbc:postgresql://localhost:5432/usuario_db
spring.datasource.username=postgres
spring.datasource.password=jeiner1379
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuración de JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Registro del cliente Google
spring.security.oauth2.client.registration.google.client-id=312781312924-0q9qd5du99latfpci34fbu968o1vj03t.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Configuración del proveedor Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://www.googleapis.com/oauth2/v4/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

